export const STATES = [
  { code: '-1', name: 'All India' },
  { code: 'AN', name: 'Andaman & Nicobar' },
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihar' },
  { code: 'CG', name: 'Chhattisgarh' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'DD', name: 'Dadra & Nagar Haveli and Daman & Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' },
  { code: 'HP', name: 'Himachal Pradesh' },
  { code: 'HR', name: 'Haryana' },
  { code: 'JH', name: 'Jharkhand' },
  { code: 'JK', name: 'Jammu & Kashmir' },
  { code: 'KA', name: 'Karnataka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'MH', name: 'Maharashtra' },
  { code: 'ML', name: 'Meghalaya' },
  { code: 'MN', name: 'Manipur' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nagaland' },
  { code: 'OR', name: 'Odisha' },
  { code: 'PB', name: 'Punjab' },
  { code: 'PY', name: 'Puducherry' },
  { code: 'RJ', name: 'Rajasthan' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TG', name: 'Telangana' },
  { code: 'TN', name: 'Tamil Nadu' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UK', name: 'Uttarakhand' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'WB', name: 'West Bengal' },
];

export const VEHICLE_CATEGORIES = [
  { code: '2WIC', name: '2W-Invalid Carriage' },
  { code: '2WN', name: '2W-Non Transport' },
  { code: '2WT', name: '2W-Transport' },
  { code: '3WIC', name: '3W-Invalid Carriage' },
  { code: '3WN', name: '3W-Non Transport' },
  { code: '3WT', name: '3W-Transport' },
  { code: '4WIC', name: '4W-Invalid Carriage' },
  { code: 'HGV', name: 'Heavy Goods Vehicle' },
  { code: 'HMV', name: 'Heavy Motor Vehicle' },
  { code: 'HPV', name: 'Heavy Passenger Vehicle' },
  { code: 'LGV', name: 'Light Goods Vehicle' },
  { code: 'LMV', name: 'Light Motor Vehicle' },
  { code: 'LPV', name: 'Light Passenger Vehicle' },
  { code: 'MGV', name: 'Medium Goods Vehicle' },
  { code: 'MMV', name: 'Medium Motor Vehicle' },
  { code: 'MPV', name: 'Medium Passenger Vehicle' },
  { code: 'OTH', name: 'Others' },
];

export const Y_AXIS_OPTIONS = [
  { value: 'Vehicle Category', label: 'Vehicle Category' },
  { value: 'Vehicle Class', label: 'Vehicle Class' },
  { value: 'Norms', label: 'Norms' },
  { value: 'Fuel', label: 'Fuel' },
  { value: 'Maker', label: 'Maker' },
  { value: 'State', label: 'State' },
];

export const X_AXIS_OPTIONS = [
  { value: 'Month Wise', label: 'Month Wise' },
  { value: 'Calendar Year', label: 'Calendar Year' },
  { value: 'Financial Year', label: 'Financial Year' },
];

export const FUEL_TYPES = [
  { id: '1', name: 'Petrol' },
  { id: '2', name: 'Diesel' },
  { id: '3', name: 'CNG' },
  { id: '4', name: 'LPG' },
  { id: '5', name: 'Electric(BOV)' },
  { id: '6', name: 'Petrol/CNG' },
  { id: '8', name: 'Petrol/LPG' },
  { id: '10', name: 'Diesel/CNG' },
  { id: '11', name: 'CNG Only' },
  { id: '12', name: 'Petrol/Hybrid' },
  { id: '13', name: 'Diesel/Hybrid' },
  { id: '14', name: 'Diesel/Electric' },
  { id: '15', name: 'Petrol/Electric' },
  { id: '16', name: 'CNG/Electric' },
  { id: '17', name: 'LPG/Electric' },
  { id: '18', name: 'Methanol' },
  { id: '19', name: 'Ethanol' },
  { id: '20', name: 'Solar' },
  { id: '21', name: 'Hydrogen Fuel Cell' },
  { id: '99', name: 'Others' },
];

export const NORMS = [
  { id: '1', name: 'Not Applicable' },
  { id: '2', name: 'BHARAT STAGE II' },
  { id: '3', name: 'BHARAT STAGE III' },
  { id: '4', name: 'BHARAT STAGE IV' },
  { id: '5', name: 'BHARAT STAGE V' },
  { id: '6', name: 'BHARAT STAGE VI' },
  { id: '99', name: 'Others' },
];

export const MAKERS = [
  'MARUTI SUZUKI INDIA LTD',
  'HYUNDAI MOTOR INDIA LTD',
  'TATA MOTORS LTD',
  'MAHINDRA & MAHINDRA LTD',
  'KIA INDIA PVT LTD',
  'TOYOTA KIRLOSKAR MOTOR PVT LTD',
  'HONDA CARS INDIA LTD',
  'MG MOTOR INDIA PVT LTD',
  'SKODA AUTO VOLKSWAGEN INDIA PVT LTD',
  'RENAULT INDIA PVT LTD',
  'NISSAN MOTOR INDIA PVT LTD',
  'FORD INDIA PVT LTD',
  'HERO MOTOCORP LTD',
  'HONDA MOTORCYCLE AND SCOOTER INDIA PVT LTD',
  'TVS MOTOR COMPANY LTD',
  'BAJAJ AUTO LTD',
  'ROYAL ENFIELD',
  'SUZUKI MOTORCYCLE INDIA PVT LTD',
  'YAMAHA MOTOR INDIA PVT LTD',
  'OLA ELECTRIC TECHNOLOGIES PVT LTD',
  'ATHER ENERGY PVT LTD',
  'BYD INDIA PVT LTD',
  'MERCEDES BENZ INDIA PVT LTD',
  'BMW INDIA PVT LTD',
  'AUDI INDIA',
  'VOLVO AUTO INDIA PVT LTD',
  'ASHOK LEYLAND LTD',
  'EICHER MOTORS LTD',
  'FORCE MOTORS LTD',
  'ISUZU MOTORS INDIA PVT LTD',
];
